name = "chip"
version = "0.1.7"
description = "A Gleam registry library"
licences = ["Apache-2.0"]

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
repository = { type = "github", user = "chouzar", repo = "chip" }
gleam = ">= 0.32.0"
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.32.1"

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_erlang = "~> 0.23.1"
gleam_otp = "~> 0.8.0"
