name = "chip"
version = "0.8.3"
description = "A Gleam registry library"
licences = ["Apache-2.0"]

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
repository = { type = "github", user = "chouzar", repo = "chip" }
gleam = ">= 1.0.0"
# links = [{ title = "Website", href = "https://gleam.run" }]

[documentation]
pages = [
  { title = "General use-cases", path = "guides/general-use-cases.html", source = "./guides/general-use-cases.md" },
  { title = "Add to a Supervisor", path = "guides/chip-as-part-of-a-supervision-tree.html", source = "./guides/chip-as-part-of-a-supervision-tree.md" },
  { title = "As a local PubSub", path = "guides/chip-as-a-local-pubsub.html", source = "./guides/chip-as-a-local-pubsub.md" },
  { title = "Wrapping up Chip", path = "guides/wrapping-up-chip.html", source = "./guides/wrapping-up-chip.md" },
]

[dependencies]
gleam_stdlib = ">= 0.36.0 and < 2.0.0"
gleam_erlang = ">= 0.24.0 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
benchee = ">= 1.3.0 and < 2.0.0"
